[[ $- == *i* ]] || return

## BASH PROMPT
# git_prompt_info accepts 0 or 1 arguments (i.e., format string)
# returns text to add to bash PS1 prompt (includes branch name)
git_prompt_info() {
  local g="$(git rev-parse --git-dir 2>/dev/null)"
  if [ -n "$g" ]; then
    local r
    local b
    local d
    local s
    # Rebasing
    if [ -d "$g/rebase-apply" ]; then
      if test -f "$g/rebase-apply/rebasing"; then
        r="|REBASE"
      fi
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    # Interactive rebase
    elif [ -f "$g/rebase-merge/interactive" ]; then
      r="|REBASE-i"
      b="$(cat "$g/rebase-merge/head-name")"
    # Merging
    elif [ -f "$g/MERGE_HEAD" ]; then
      r="|MERGING"
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    else
      if [ -f "$g/BISECT_LOG" ]; then
        r="|BISECTING"
      fi
      if ! b="$(git symbolic-ref HEAD 2>/dev/null)"; then
        if ! b="$(git describe --exact-match HEAD 2>/dev/null)"; then
          b="$(cut -c1-7 "$g/HEAD")..."
        fi
      fi
    fi

    # Dirty Branch
    local newfile='?? '
    if [ -n "$ZSH_VERSION" ]; then
      newfile='\?\? '
    fi
    d=''
    s=$(git status --porcelain 2>/dev/null)
    [[ $s =~ "$newfile" ]] && d+='+'
    [[ $s =~ "M " ]] && d+='*'
    [[ $s =~ "D " ]] && d+='-'

    printf "${1-"(%s) "}" "${b##refs/heads/}$r$d"
  fi
}

[ -z "$PS1" ] || stty -ixon
[ -z "$PS1" ] || export PS1="\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;36m\]\W\[\033[00m\]\$(git_prompt_info '(%s)')\[\e[34m\]→\[\e[m\] "

## SHELL CONFIGURATION
# Bash history
export HISTCONTROL=erasedups # Don't store duplicates
export HISTIGNORE="%*"
export HISTSIZE=10000 # Store 10,000 history entries
shopt -s histappend   # Append to history file

# Prevent bash deprecation warnings from Apple switching to zsh because GPLv3
# is fucking impossible for them to imagine, heaven forfend
export BASH_SILENCE_DEPRECATION_WARNING=1

# Editors
export CLICOLOR=1
export EDITOR=vim
export LESS="FRX"
export LSCOLORS=gxgxcxdxbxegedabagacad
export PSQL_EDITOR='vim -c"setf sql"'
export RI="--format ansi -T"
export VISUAL=vim

# Keyboard navigation
bind 'set bind-tty-special-chars off'
bind '"\ep": history-search-backward'
bind '"\en": history-search-forward'
bind '"\C-w": backward-kill-word'
bind '"\C-q": "%-\n"'

# Bash autocompletion (including git)
if [ -f '/usr/local/etc/bash_completion.d' ]; then source /usr/local/etc/bash_completion.d; fi
source ~/.flerm/bash/git-completion.bash

## SHORTCUTS
# Git aliases
alias gap='git add -p'
alias gd='git diff'
alias glod='git log --oneline --decorate'
alias gpu='git stash && git pull --rebase origin HEAD && git stash pop'
alias gst='git status'

# Editor aliases
alias edit="vim"
alias vi="vim"

# Kill and status aliases
alias die="killall -HUP -9"
alias is="ps ax -o pid,comm |grep "
alias wat="lsof |grep "

# Helpful aliases
alias be="bundle exec"
alias ls="ls -lah"
alias yarn="yarn --silent"

## HELPER FUNCTIONS
# Client folder navigation
cdc() {
  cd ~/Clients/$1
}

# Ack, Ag, and replacements
alias ag='ag --path-to-ignore ~/.ignore'
gsub() {
  if [ $# -lt 2 ]; then
    echo "Usage: gsub PATTERN REPLACEMENT [LOCATION]"
    return
  fi

  ag -l "$1" $3 | xargs perl -pi -E "s/$1/$2/g"
}

# Tmux helper
tm() {
  if [ $# -lt 1 ]; then
    echo "Usage: tm PROJECT"
    return
  fi

  tmux -CC attach -t "$1" || tmux -CC new -s $1
}

## DEV ENVIRONMENT
# Local bin path
if [ -d ~/.bin ]; then export PATH="~/.bin/:$PATH"; fi

# VSCode editor
vsc="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
if [ -d "$vsc" ]; then export PATH="$PATH:$vsc"; fi

# Android development
if [ -d ~/Library/Android/sdk ]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export PATH=$PATH:$ANDROID_HOME/tools
  export PATH=$PATH:$ANDROID_HOME/platform-tools
  export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
fi

# JS development
if [ -d ~/.yarn/bin ]; then export PATH="~/.yarn/bin/:$PATH"; fi
if [ -d ~/.nvm ]; then
  export NVM_DIR="$HOME/.nvm"                                                                               # This is self-explanatory; IDK what it's used for but there you have it
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"                                       # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
fi

# Ruby development
export WD_CHROME_VERSION="90.0.4425"
if [ -d ~/.rbenv/bin ]; then export PATH="$HOME/.rbenv/bin:$PATH"; fi
if [ $(command -v rbenv) ]; then eval "$(rbenv init -)"; fi
if [ $(command -v brew) ]; then export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"; fi

# Rust development
if [ -d ~/.cargo/bin ]; then export PATH="$HOME/.cargo/bin:$PATH"; fi
if [ -f ~/.cargo/env ]; then source $HOME/.cargo/env; fi

# GCP
gcp_path="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
if [ -f $gcp_path ]; then source $gcp_path; fi
gcp_completions="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
if [ -f $gcp_completions ]; then source $gcp_completions; fi
