[[ $- == *i* ]] || return

# git_prompt_info accepts 0 or 1 arguments (i.e., format string)
# returns text to add to bash PS1 prompt (includes branch name)
git_prompt_info () {
  local g="$(git rev-parse --git-dir 2>/dev/null)"
  if [ -n "$g" ]; then
    local r
    local b
    local d
    local s
    # Rebasing
    if [ -d "$g/rebase-apply" ] ; then
      if test -f "$g/rebase-apply/rebasing" ; then
        r="|REBASE"
      fi
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    # Interactive rebase
    elif [ -f "$g/rebase-merge/interactive" ] ; then
      r="|REBASE-i"
      b="$(cat "$g/rebase-merge/head-name")"
    # Merging
    elif [ -f "$g/MERGE_HEAD" ] ; then
      r="|MERGING"
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    else
      if [ -f "$g/BISECT_LOG" ] ; then
        r="|BISECTING"
      fi
      if ! b="$(git symbolic-ref HEAD 2>/dev/null)" ; then
        if ! b="$(git describe --exact-match HEAD 2>/dev/null)" ; then
          b="$(cut -c1-7 "$g/HEAD")..."
        fi
      fi
    fi

    # Dirty Branch
    local newfile='?? '
    if [ -n "$ZSH_VERSION" ]; then
      newfile='\?\? '
    fi
    d=''
    s=$(git status --porcelain 2> /dev/null)
    [[ $s =~ "$newfile" ]] && d+='+'
    [[ $s =~ "M " ]] && d+='*'
    [[ $s =~ "D " ]] && d+='-'

    printf "${1-"(%s) "}" "${b##refs/heads/}$r$d"
  fi
}

# Store 10,000 history entries
export HISTSIZE=10000
# Don't store duplicates
export HISTCONTROL=erasedups
# Append to history file
shopt -s histappend

if ! [ -x "$(command -v code)" ]; then
  VISUAL=code
elif ! [ -x "$(command -v nvim)" ]; then
  VISUAL=vim
else
  VISUAL=nvim
fi
EDITOR="$VISUAL"
LESS="FRX"
RI="--format ansi -T"
PSQL_EDITOR='nvim -c"setf sql"'
CLICOLOR=1
LSCOLORS=gxgxcxdxbxegedabagacad

export VISUAL EDITOR LESS RI PSQL_EDITOR CLICOLOR LSCOLORS

bind 'set bind-tty-special-chars off'
bind '"\ep": history-search-backward'
bind '"\en": history-search-forward'
bind '"\C-w": backward-kill-word'

export HISTIGNORE="%*"
bind '"\C-q": "%-\n"'

[ -z "$PS1" ] || stty -ixon
[ -z "$PS1" ] || export PS1="\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;36m\]\W\[\033[00m\]\$(git_prompt_info '(%s)')$ "

# Git aliases
alias gap='git add -p'
alias glod='git log --oneline --decorate'
alias gst='git status'
alias gd='git diff'
alias gpu='git stash && git pull --rebase origin HEAD && git stash pop'

# Editor aliases
alias edit="nvim"
alias vi="nvim"

# Kill and status aliases
alias die="killall -HUP -9"
alias is="ps ax -o pid,comm |grep "
alias wat="lsof |grep "

# Bash overrides
alias ls="ls -la"
alias be="bundle exec"

# Bash autocompletion (including git)
if [ -f '/usr/local/etc/bash_completion.d' ]; then source /usr/local/etc/bash_completion.d; fi
source ~/.flerm/bash/git-completion.bash

# Ack, Ag, and replacements
gsub() {
  if [ $# -lt 2 ]
  then
    echo "Usage: gsub PATTERN REPLACEMENT [LOCATION]"
    return
  fi

  ag -l "$1" $3 | xargs perl -pi -E "s/$1/$2/g"
}

alias ag='ag --path-to-ignore ~/.ignore'

# Tmux helper
tm() {
  if [ $# -lt 1 ]
  then
    echo "Usage: tm PROJECT"
    return
  fi

  tmux -CC attach -t "$1" || tmux -CC new -s $1
}

# Android development
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

# JS development
export PATH="$HOME/.yarn/bin:$PATH"

# Ruby development
eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/flip/bin/google-cloud-sdk/path.bash.inc' ]; then source '/Users/flip/bin/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/flip/bin/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/flip/bin/google-cloud-sdk/completion.bash.inc'; fi

# Add local bin path if it exists
if [ -d ~/.bin ]; then export PATH="~/.bin/:$PATH"; fi

# VSCode, if'n it exists
if [ -d '/Applications/Visual Studio Code.app/Contents/Resources/app/bin' ]; then export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"; fi
