[[ $- == *i* ]] || return

# git_prompt_info accepts 0 or 1 arguments (i.e., format string)
# returns text to add to bash PS1 prompt (includes branch name)
git_prompt_info() {
  local g="$(git rev-parse --git-dir 2>/dev/null)"
  if [ -n "$g" ]; then
    local r
    local b
    local d
    local s
    # Rebasing
    if [ -d "$g/rebase-apply" ]; then
      if test -f "$g/rebase-apply/rebasing"; then
        r="|REBASE"
      fi
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    # Interactive rebase
    elif [ -f "$g/rebase-merge/interactive" ]; then
      r="|REBASE-i"
      b="$(cat "$g/rebase-merge/head-name")"
    # Merging
    elif [ -f "$g/MERGE_HEAD" ]; then
      r="|MERGING"
      b="$(git symbolic-ref HEAD 2>/dev/null)"
    else
      if [ -f "$g/BISECT_LOG" ]; then
        r="|BISECTING"
      fi
      if ! b="$(git symbolic-ref HEAD 2>/dev/null)"; then
        if ! b="$(git describe --exact-match HEAD 2>/dev/null)"; then
          b="$(cut -c1-7 "$g/HEAD")..."
        fi
      fi
    fi

    # Dirty Branch
    local newfile='?? '
    if [ -n "$ZSH_VERSION" ]; then
      newfile='\?\? '
    fi
    d=''
    s=$(git status --porcelain 2>/dev/null)
    [[ $s =~ "$newfile" ]] && d+='+'
    [[ $s =~ "M " ]] && d+='*'
    [[ $s =~ "D " ]] && d+='-'

    printf "${1-"(%s) "}" "${b##refs/heads/}$r$d"
  fi
}

# Store 10,000 history entries
export HISTSIZE=10000

# Don't store duplicates
export HISTCONTROL=erasedups

# Append to history file
shopt -s histappend

# Set up editors
export EDITOR=vim
export VISUAL=vim
export LESS="FRX"
export RI="--format ansi -T"
export PSQL_EDITOR='nvim -c"setf sql"'
export CLICOLOR=1
export LSCOLORS=gxgxcxdxbxegedabagacad

# Prevent bash deprecation warnings from Apple switching to zsh because GPLv3 is fucking impossible for them to imagine, heaven forfend
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set up keyboard navigation
bind 'set bind-tty-special-chars off'
bind '"\ep": history-search-backward'
bind '"\en": history-search-forward'
bind '"\C-w": backward-kill-word'

# I don't know, some history stuff
export HISTIGNORE="%*"
bind '"\C-q": "%-\n"'

[ -z "$PS1" ] || stty -ixon
[ -z "$PS1" ] || export PS1="\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;36m\]\W\[\033[00m\]\$(git_prompt_info '(%s)')\[\e[32m\]→\[\e[m\] "

# Git aliases
alias gap='git add -p'
alias glod='git log --oneline --decorate'
alias gst='git status'
alias gd='git diff'
alias gpu='git stash && git pull --rebase origin HEAD && git stash pop'

# Editor aliases
alias edit="nvim"
alias vi="nvim"

# Kill and status aliases
alias die="killall -HUP -9"
alias is="ps ax -o pid,comm |grep "
alias wat="lsof |grep "

# Bash overrides
alias yarn="yarn --silent"
alias ls="ls -la"

# Helpful aliases
alias be="bundle exec"

# Bash autocompletion (including git)
if [ -f '/usr/local/etc/bash_completion.d' ]; then source /usr/local/etc/bash_completion.d; fi
source ~/.flerm/bash/git-completion.bash

# Client folder navigation
cdc() {
  cd ~/Clients/$1
}

# Ack, Ag, and replacements
gsub() {
  if [ $# -lt 2 ]; then
    echo "Usage: gsub PATTERN REPLACEMENT [LOCATION]"
    return
  fi

  ag -l "$1" $3 | xargs perl -pi -E "s/$1/$2/g"
}

alias ag='ag --path-to-ignore ~/.ignore'

# Tmux helper
tm() {
  if [ $# -lt 1 ]; then
    echo "Usage: tm PROJECT"
    return
  fi

  tmux -CC attach -t "$1" || tmux -CC new -s $1
}

# Android development
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

# JS development
if [ -d ~/.yarn/bin ]; then export PATH="~/.yarn/bin/:$PATH"; fi
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"                                       # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

# Ruby development
if [ -d ~/.rbenv/bin ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
fi

if [ $(command -v rbenv) ]; then
  eval "$(rbenv init -)"
fi

# Add local bin path if it exists
if [ -d ~/.bin ]; then export PATH="~/.bin/:$PATH"; fi

# VSCode, if'n it exists
if [ -d '/Applications/Visual Studio Code.app/Contents/Resources/app/bin' ]; then export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"; fi

# Set up Rust, if need be
if [ -d ~/.cargo ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
  source $HOME/.cargo/env
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/flip/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/flip/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/flip/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/flip/Downloads/google-cloud-sdk/completion.bash.inc'; fi
