set nocompatible               " be iMproved
filetype off                   " required!

" Import bundles using vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
so ~/.vim/plugins.vim

syntax on
filetype plugin indent on

" GUI configuration
let &t_Co=256
colorscheme molokai
set number
set guifont=Monaco:h14
set visualbell
set splitright
set splitbelow

set guioptions-=T guioptions-=e guioptions-=L guioptions-=r
set shell=bash
syntax on

" Tab and wrap configuration
set expandtab
set shiftwidth=2
set softtabstop=2
set smarttab
set nocindent
set wrap

" Buffer autocommands
autocmd BufWritePre * :TrailerTrim

" Read specific files real smaht-like
let g:jsx_ext_required = 0
autocmd BufNewFile,BufRead *.json set ft=javascript
autocmd BufNewFile,BufRead *.slim set ft=slim

" Read Filefiles as their intended format
autocmd BufNewFile,BufRead Gemfile set ft=ruby
autocmd BufNewFile,BufRead Guardfile set ft=ruby
autocmd BufNewFile,BufRead Podfile set ft=ruby
autocmd BufNewFile,BufRead Procfile set ft=yaml

" NERDCommenter shortcuts
nmap \\ <Plug>NERDCommenterInvert
xmap \\ <Plug>NERDCommenterInvert

" Pane navigation shortcuts
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l
nmap , 10<C-W>>
nmap . 10<C-W><

" Disable arrow keys outside of editing
nmap <Down> <>
nmap <Up> <>
nmap <Left> <>
nmap <Right> <>

" Turn on NERDTree
map <leader><tab> :NERDTreeTabsToggle<CR>

set ttimeoutlen=50  " Make Esc work faster

" Make the cursor pretty and friendly and nice
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=2\x7"
set cursorline

" Extend HTML indentation
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

" CTRLP configuration
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ } " Open in tabs
set wildignore+=*/node_modules/*,*/tmp/*,*/build/*,*.so,*.swp,*.zip,*.pyc,*/dist/* " Ignore garbage

" CMD+V - sigh. Someday.
"map <Leader>v  <C-O>:set paste<CR><C-r>*<C-O>:set nopaste<CR>
set backspace=indent,eol,start

" Syntastic madness
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

