set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

so ~/.vim/plugins.vim

" PATHOGEN
syntax on
filetype plugin indent on

" GUI configuration
let &t_Co=256
colorscheme molokai
set number
set guifont=Monaco:h14
set visualbell
set splitright
set splitbelow

set guioptions-=T guioptions-=e guioptions-=L guioptions-=r
set shell=bash
syntax on

set expandtab
set shiftwidth=2
set softtabstop=2
set smarttab
set cindent
set wrap

" Buffer autocommands
autocmd BufWritePre * :Trim

" Read JSON files as JavaScript
autocmd BufNewFile,BufRead *.json set ft=javascript

" Read Podfiles as Ruby
autocmd BufNewFile,BufRead Guardfile set ft=ruby
autocmd BufNewFile,BufRead Podfile set ft=ruby
autocmd BufNewFile,BufRead Procfile set ft=yaml

" NERDCommenter shortcuts
nmap \\           <Plug>NERDCommenterInvert
xmap \\           <Plug>NERDCommenterInvert

" Pane navigation shortcuts
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l
nmap , 10<C-W>>
nmap . 10<C-W><

" Disable arrow keys to force me to LEARN
nmap <Down> <>
nmap <Up> <>
nmap <Left> <>
nmap <Right> <>

"map <leader><tab> :BufExplorer<CR>
map <leader><tab> :NERDTreeTabsToggle<CR>

set ttimeoutlen=50  " Make Esc work faster

" Make the cursor pretty and friendly and nice
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=2\x7"
set cursorline

" Add helpful Rails commands for common patterns
autocmd User Rails nnoremap <buffer> <D-r> :<C-U>Rake<CR>
autocmd User Rails nnoremap <buffer> <D-R> :<C-U>.Rake<CR>
autocmd User Rails Rnavcommand decorator app/decorators -suffix=_decorator.rb -default=model()
autocmd User Rails Rnavcommand presenter app/presenters -suffix=_presenter.rb -default=model()
autocmd User Rails Rnavcommand uploader app/uploaders -suffix=_uploader.rb -default=model()
autocmd User Rails Rnavcommand steps features/step_definitions spec/steps -suffix=_steps.rb -default=web
autocmd User Rails Rnavcommand blueprint spec/blueprints -suffix=_blueprint.rb -default=model()
autocmd User Rails Rnavcommand factory spec/factories -suffix=_factory.rb -default=model()
autocmd User Rails Rnavcommand fabricator spec/fabricators -suffix=_fabricator.rb -default=model()
autocmd User Rails Rnavcommand feature features -suffix=.feature -default=cucumber
autocmd User Rails Rnavcommand serializer app/serializers -suffix=_serializer.rb -default=model()
autocmd User Rails Rnavcommand support spec/support features/support -default=env
autocmd User Rails Rnavcommand worker app/workers -suffix=_worker.rb -default=model()
autocmd User Rails Rnavcommand javascript app/assets/javascripts -suffix=.js -default=model()
autocmd User Rails Rnavcommand less app/assets/stylesheets -suffix=.less -default=model()
autocmd User Rails Rnavcommand stylesheet app/assets/stylesheets -suffix=.scss -default=model()
autocmd User Rails Rnavcommand task lib/tasks -suffix=.rake -default=model()
autocmd User Fugitive command! -bang -bar -buffer -nargs=* Gpr :Git<bang> pull --rebase <args>$

" Extend HTML indentation
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

" CTRLP opens in tabs instead of the current buffer
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }

" CMD+V - sigh. Someday.
"map <Leader>v  <C-O>:set paste<CR><C-r>*<C-O>:set nopaste<CR>
